case_groups:
# pdf
- id: 技能_单文档问答pdf
  url: /api/v1/process/
  case_name: 单文档问答_pdf
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"合同签约日期","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/合同.pdf"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt
# md
- id: 技能_单文档问答md
  url: /api/v1/process/
  case_name: 单文档问答_md
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"谁是我们的敌人？","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/test.md"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt
#ppt
- id: 技能_单文档问答ppt
  url: /api/v1/process/
  case_name: 单文档问答_ppt
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"开学日期","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/test.ppt"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt
#pptx
- id: 技能_单文档问答pptx
  url: /api/v1/process/
  case_name: 单文档问答_pptx
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"创建人","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/pptx.pptx"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt
#doc
- id: 技能_单文档问答doc
  url: /api/v1/process/
  case_name: 单文档问答_doc
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"王传军的毕业学校","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/个人简历doc.doc"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt
#docx
- id: 技能_单文档问答docx
  url: /api/v1/process/
  case_name: 单文档问答_docx
  method: post
  tweaks: {"InputFileNode-050e5": {"file_path":""}}
  body: {
    "inputs": {
      "query":"文档编写日期","id":"RetrievalQA-qH6Mk"
      },
    "file_path":"/Users/sara/Desktop/DataElem/dev/bisheng-test/data/test_data/开发实践.docx"
    }
  expectresult: {"status": "success"}
  expectdata: case_flow/test_singledocument_pdf.txt